### ISSUE TITLE
Nordic Thingy 52 unable to capture the RSSI value

### ISSUE THREAD

**Issue by Xiryl** [NordicSemiconductor/Android-Nordic-Thingy#19] opened 2020-02-19 07:45 UTC
Hi, everybody,

I managed, through the Nordic library for Android `thingylib` ([github](https://github.com/NordicSemiconductor/Android-Nordic-Thingy/tree/master/thingylib)) , to connect to thingy52 and receive in the callback listener `ThingyListener`  the information about the device (e.g. `onGravityVectorChangedEvent`, `onAccelerometerValueChangedEvent`, `onGyroscopeValueChangedEvent`, and so on...).

What I can't do (and I can't find how to do) is how I can get the information about the connection with the device, exactly the RSSI values. 

Using the [BluetoothLeScannerCompat](https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library), inside the `onBatchScanResults` scan callback, I detect the thingy52 bluetooth device, and their RSSI value, but if I set a high scan frequency, for example `.setReportDelay(10)`, it almost always does not detect devices.

```java
 ScanSettings scanSettings = new ScanSettings.Builder()
                .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY)
                .setReportDelay(10) // frequency of scan
                .setUseHardwareBatchingIfSupported(false)
                .build();
```

My need is to get at a frequency of `10Hz`, or `100Hz` the RSSI value of the nordic thingy52, which I can't get from the `ThingyListener` events. 

How can I do it? 
Thank you in advance.

**Comment by philips77** [comment] 2020-02-20 11:44
Duplicate of https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library/issues/77

**Closed as completed by philips77** 2020-02-20 11:44 UTC
